<?xml version="1.0" encoding="UTF-8"?>

<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro" >


    <xacro:include filename="common_properties.xacro" />
    <xacro:include  filename="mobile_base_gazebo.xacro" />
    <xacro:include filename="camera.xacro" />

    <xacro:property name="base_length" value="0.7" />
    <xacro:property name="base_width" value="0.4" />
    <xacro:property name="base_height" value="0.2" />
    <xacro:property name="wheel_radius" value="0.1" />
    <xacro:property name="wheel_length" value="0.05" />

    <!-- to comment use ctrl+/ -->
    <!-- <xacro:macro name="example_macro" params="a b c"> -->
        <!-- <link name="dummy_link"> -->
            <!-- <visual> -->
                <!-- <geometry> -->
                    <!-- <box size="${a} ${b} ${c}" /> -->
                <!-- </geometry> -->
            <!-- </visual> -->
        <!-- </link> -->
    <!-- </xacro:macro>  -->

    <!-- <xacro:example_macro a="2" b="3" c="4" /> -->



    <link name="base_footprint" />
  

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" /> 
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
            <material name="blue" />    
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" /> 
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />

        </collision>
        <xacro:box_inertia m="10.0" l="${base_length}" w="${base_width}" h="${base_height}" 
                           xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
    </link>

    <link name="second_link">
    <visual>
        <geometry>
            <cylinder radius="0.025" length="0.2" />
        </geometry>
        <origin xyz="0 0 0.1" rpy="0 0 0" />
        <material name="grey" />

    <collision>
        <geometry>
            <cylinder radius="0.025" length="0.2" /> 
        </geometry>
        <origin xyz="0 0 0.1" rpy="0 0 0" />

    </collision>    

    </visual>    
    <xacro:cylinder_inertia m="1.0" r="0.025" h="0.2" 
                                xyz="0 0 0.1" rpy="0 0 0" />
    </link>

    <link name="thrid_link">
        <visual>
            <geometry>
                <box size="0.1 0.1 0.1" /> 
            </geometry>
            <origin xyz="0 0 0.05" rpy="0 0 0" />
            <material name="blue" />
        </visual>
        <collision>
            <geometry>
                <box size="0.1 0.1 0.1" /> 
            </geometry>
            <origin xyz="0 0 0.05" rpy="0 0 0" />

        </collision>
        <xacro:box_inertia m="0.2" l="0.1" w="0.1" h="0.1" 
                           xyz="0 0 0.05" rpy="0 0 0" />
    </link>

    <link name="base_of_arm">
        <visual>
            <geometry>
                <cylinder length="0.05" radius="0.08" /> 
            </geometry>
            <origin xyz="0 0 0.025" rpy="0 0 0" />
            <material name="red" />
        </visual>
        <collision>
            <origin rpy="0 0 0.025" xyz="0 0 0" />
            <geometry>
              <cylinder length="0.05" radius="0.08" />
            </geometry>
            <material name="red"/>
        </collision>
        <xacro:cylinder_inertia m="0.5" r="0.08" h="0.05" 
                                xyz="0 0 0.025" rpy="0 0 0" />
    </link>

    <link name="arm1">
        <visual>
            <geometry>
                <mesh filename="file:///home/mitesh/Downloads/lesson_urdf-master/meshes/visual/arm_link.stl" scale="0.8 0.8 0.8" />
            </geometry>              
          <origin xyz="0 0 0" rpy="0 0 0" />
          <material name="red"/>
        </visual>
        <collision>
            <geometry>
              <mesh filename="file:///home/mitesh/Downloads/lesson_urdf-master/meshes/collision/arm_link.stl" scale="0.8 0.8 0.8" />
            </geometry>
            <material name="red"/>
          </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <mass value="1" />
            <inertia ixx="0.3" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
          </inertial>
      </link>

      <link name="arm2">
        <visual>
          <geometry>
            <mesh filename="file:///home/mitesh/Downloads/lesson_urdf-master/meshes/visual/arm_link.stl" scale="0.8 0.8 0.8" />
          </geometry>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <material name="red"/>
        </visual>
        <collision>
            <geometry>
              <mesh filename="file:///home/mitesh/Downloads/lesson_urdf-master/meshes/collision/arm_link.stl" scale="0.8 0.8 0.8" />
            </geometry>
            <material name="red"/>
          </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <mass value="1" />
            <inertia ixx="0.3" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
          </inertial>
      </link>

      <link name="gripper">
        <visual>
          <geometry>
            <mesh filename="file:///home/mitesh/Downloads/lesson_urdf-master/meshes/visual/gripper.stl" scale="0.8 0.8 0.8"  />
          </geometry>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <material name="grey"/>
        </visual>  
        <collision>
            <geometry>
            <mesh filename="file:///home/mitesh/Downloads/lesson_urdf-master/meshes/visual/gripper.stl" scale="0.8 0.8 0.8"  />
            </geometry>
            <material name="grey"/>
          </collision>
        <inertial>
            <origin xyz="0 0 0.1" rpy="0 0 0" />
            <mass value="1" />
            <inertia ixx="0.05" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
          </inertial>
      </link>

    <link name="front_right_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
            <material name="grey" />
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <material name="grey"/>
        </collision>
        <xacro:cylinder_inertia m="1.0" r="${wheel_radius}" h="${wheel_length}" 
                                xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
    </link>

    <link name="back_right_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
            <material name="grey" />
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <material name="grey"/>
        </collision>
        <xacro:cylinder_inertia m="1.0" r="${wheel_radius}" h="${wheel_length}" 
                                xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
    </link>

    <link name="front_left_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
            <material name="grey" />
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <material name="grey"/>
        </collision>
        <xacro:cylinder_inertia m="1.0" r="${wheel_radius}" h="${wheel_length}" 
                                xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
    </link>

    <link name="back_left_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
            <material name="grey" />
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <material name="red"/>
        </collision>
        <xacro:cylinder_inertia m="1.0" r="${wheel_radius}" h="${wheel_length}" 
                                xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
    </link>


    <joint name="base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
    </joint>


    <joint name="base_second_joint" type="fixed">
        <parent link="base_link" />
        <child link="second_link" />
        <origin xyz="0 0 0.2" rpy="0 0 0" />
    </joint>

    <joint name="second_third_joint" type="continuous">
        <parent link="second_link" />
        <child link="thrid_link" />
        <origin xyz="0 0 0.2" rpy="0 0 0" />
        <axis xyz="0 0 1" />
    </joint>

    <joint name="base_front_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="front_right_wheel_link" />
        <origin xyz="${base_length / 4.0} ${-(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_back_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="back_right_wheel_link" />
        <origin xyz="${-base_length / 4.0} ${-(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_front_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="front_left_wheel_link" />
        <origin xyz="${base_length / 4.0} ${(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_back_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="back_left_wheel_link" />
        <origin xyz="${-base_length / 4.0} ${(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_base_arm_joint" type="fixed">
        <parent link="base_link" />
        <child link="base_of_arm" />
        <origin xyz="${base_length / 3.0} 0.1 0.2" rpy="0 0 0" />
    </joint>

    <joint name="base_arm_arm1_joint" type="revolute">
        <parent link="base_of_arm" />
        <child link="arm1" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <axis xyz="0 0 1" />
        <limit lower="0" upper="${pi / 2.0}" effort="100" velocity="100" />
      </joint>

      <joint name="arm1_arm2_joint" type="revolute">
        <parent link="arm1" />
        <child link="arm2" />
        <origin xyz="0.4 0 0" rpy="0 0 0" />
        <axis xyz="0 0 1" />
        <limit lower="0" upper="${pi / 2.0}" effort="100" velocity="100" />
      </joint>

      <joint name="arm2_gripper_joint" type="revolute">
        <parent link="arm2" />
        <child link="gripper" />
        <origin xyz="0.38 -0.005 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <limit lower="0" upper="${pi / 2.0}" effort="100" velocity="100" />
      </joint>
      





</robot>